In [2]:
import numpy as np

In [3]:
mx_1s = np.array([[1,1,1,],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
#matrix

In [5]:
mx_1s = np.ones(5)
print(mx_1s)
#ones((row,column)) used to create multiple rows and columns

[1. 1. 1. 1. 1.]


In [6]:
mx_1s.dtype
#ones() stores float values

dtype('float64')

In [7]:
mx_1s = np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
#changing the type of data to int
#np.ones(shape,dtype=None,order='c')
mx_1s = np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [9]:
#To create a matrix with only zeros zeros((row,col),dtype) is used
mx_0s = np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [10]:
mx_0s = np.zeros((4,6),dtype=bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [11]:
mx_0s = np.zeros((4,6),dtype=str)
print(mx_0s)
#empty strings are printed

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [12]:
em_str = ''
print(bool(em_str))

False


In [13]:
#if empty string is converted to bool result will be false
em_mx = np.empty((3,3))
print(em_mx)
#empty() matrix can contain any random value

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]
