In [1]:
import numpy as np


In [2]:
arr1 = np.arange(0,10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
import random 

In [12]:
arr = np.random.randint(1,101,10)
print(arr)

[97  1 97 93 30 20 35 80 90 90]


In [17]:
arr2 = np.arange(1,13).reshape((3,4))
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
arr2.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [19]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.split(arr1,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [23]:
arr3 = np.arange(1,13).reshape(4,3)
arr4 = np.arange(13,25).reshape(4,3)
arr3 + arr4

array([[14, 16, 18],
       [20, 22, 24],
       [26, 28, 30],
       [32, 34, 36]])

In [24]:
arr3 * arr4

array([[ 13,  28,  45],
       [ 64,  85, 108],
       [133, 160, 189],
       [220, 253, 288]])

In [25]:
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
np.mean(arr3)

np.float64(6.5)

In [27]:
np.median(arr3)

np.float64(6.5)

In [29]:
np.std(arr3)

np.float64(3.452052529534663)

In [30]:
arr[0]

np.int32(97)

In [31]:
arr3[0]

array([1, 2, 3])

In [33]:
arr3[:,2]

array([ 3,  6,  9, 12])

In [34]:
arr3[0,0]

np.int64(1)

In [35]:
arr3[0:1,2]

array([3])

In [36]:
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
arr3[0:1,0:1]

array([[1]])

In [38]:
arr3[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [39]:
np.min(arr3)

np.int64(1)

In [40]:
np.max(arr3)

np.int64(12)

In [41]:
np.argmin(arr3)

np.int64(0)

In [42]:
np.argmax(arr3)

np.int64(11)

In [43]:
np.corrcoef(arr3,arr4)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])