Random Sampling with Numpy

In [1]:
#To generate random data
import numpy as np


In [2]:
import random 

In [4]:
np.random.random(1) #Gives a value in between 0 and 1 as a array

array([0.44805207])

In [5]:
np.random.random((3,3))

array([[0.75152898, 0.43962847, 0.38790542],
       [0.87986406, 0.80749605, 0.66756898],
       [0.86061609, 0.46172576, 0.16786728]])

In [ ]:
#To get random integer value
np.random.randint(1,4) 
#Here 4 is exclusive

1

In [8]:
np.random.randint(1,4,(4,4)) #Created a 2 D array

array([[3, 2, 3, 1],
       [3, 2, 2, 3],
       [2, 1, 3, 2],
       [1, 1, 1, 1]], dtype=int32)

In [9]:
np.random.randint(1,4,(2,4,4))

array([[[1, 2, 2, 2],
        [1, 1, 3, 3],
        [2, 2, 3, 2],
        [1, 1, 3, 2]],

       [[2, 2, 2, 3],
        [2, 2, 2, 3],
        [2, 1, 1, 2],
        [1, 1, 2, 3]]], dtype=int32)

In [10]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]], dtype=int32)

In [ ]:
#To use the same random value i.e used before seed() is used
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]], dtype=int32)

In [ ]:
2 ** 32 -1
#This much type of random values can be generated

4294967295

In [13]:
np.random.rand(3) # rand() can creat nd array

array([0.13145815, 0.41366737, 0.77872881])

In [ ]:
np.random.randn(3,3) #randn() Gives both positive and negative random values

array([[-1.25424191,  0.33157855, -0.30860049],
       [-0.15373549,  0.67893119, -1.91355421],
       [-0.94245806, -1.74554298, -1.02094527]])

In [15]:
x = [1,2,3,4]
np.random.choice(x)

np.int64(1)

In [16]:
np.random.choice(x)

np.int64(3)

In [17]:
np.random.choice(x)

np.int64(1)

In [18]:
for i in range(20):
    print(np.random.choice(x))

1
1
2
1
4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2


In [19]:
x

[1, 2, 3, 4]

In [20]:
#Permutation
np.random.permutation(x)

array([1, 2, 4, 3])

In [22]:
np.random.permutation(x)

array([2, 4, 3, 1])

String Operations, Comparision and information

In [24]:
ch_name = "Indian AI Production"
str1 = " Learning Python  Numpy "
np.char.add(ch_name,str1)

np.str_('Indian AI Production Learning Python  Numpy ')

In [25]:
np.char.lower(ch_name)

array('indian ai production', dtype='<U20')

In [26]:
np.char.upper(str1)

array(' LEARNING PYTHON  NUMPY ', dtype='<U24')

In [27]:
np.char.center(str1, 60)

array('                   Learning Python  Numpy                   ',
      dtype='<U60')

In [28]:
np.char.center(str1,60,fillchar = "*")

array('****************** Learning Python  Numpy ******************',
      dtype='<U60')

In [29]:
np.char.split(ch_name)

array(list(['Indian', 'AI', 'Production']), dtype=object)

In [30]:
np.char.splitlines("hello\nIndian")

array(list(['hello', 'Indian']), dtype=object)

In [31]:
str4 = "dmy"
str5 = "dmy"

In [33]:
np.char.join([":","/"],[str4,str5])

array(['d:m:y', 'd/m/y'], dtype='<U5')

In [34]:
np.char.replace(ch_name,"AI","Artificial Intelligence")

array('Indian Artificial Intellige Production', dtype='<U38')

In [35]:
np.char.equal(str4,str5)

array(True)

In [36]:
np.char.count(ch_name,"a")

np.int64(1)

In [37]:
ch_name

'Indian AI Production'

In [39]:
np.char.find(ch_name,"AI")

np.int64(7)