#NumPy Functions:

In [1]:
import numpy as np
#arrays can be created using these functions

arange()

In [2]:
#np.arange(start,end,steps)
#array with range
ar_1d = np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
even_array = np.arange(2,13,2)
print(even_array)

[ 2  4  6  8 10 12]


linspace()

In [4]:
#Same difference in all array values with in the given range
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

reshape()

In [5]:
#Change the array in different combination multidimentional array
ar_2d = ar_1d.reshape(3,4)
print(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
ar_2d = ar_1d.reshape(2,3,2)
print(ar_2d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


ravel()

In [8]:
#converts multi-dimensional array to 1D array
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

flatten()

In [9]:
#converts multi-dimensional array to 1D array
ar.flatten()
#It can take an argument i.e order = 'C'......(Learn)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

transpose()

In [10]:
#Conerts row into column and column into row
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [11]:
#transpose() can also be written as .T
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])