Python Numpy Array Concatination and split


In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [4]:
list1 = [2,4,5,6]
list2 = [1,2,3,4]
list1 + list2

[2, 4, 5, 6, 1, 2, 3, 4]

In [ ]:
arr1 + arr2 #normal addition

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [ ]:
np.concatenate((arr1,arr2))#Concatenation

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [7]:
np.concatenate((arr1,arr2),axis = 1)#Row wise concatenation

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [ ]:
np.vstack((arr1,arr2))#vertical concatenation

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [11]:
np.hstack((arr1,arr2))#horizontal concatenation

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [12]:
np.hstack((arr1,arr2,arr1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

In [ ]:
np.split(arr1,2) #splits the array and store the parts(multiple arrays) in a list

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [14]:
list1 = np.split(arr1,2)
type(list1)

list

In [15]:
list1[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
type(list1[0])

numpy.ndarray

In [17]:
np.split(arr1,2,axis = 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [18]:
d1 = np.array([4,7,1,3,9])

In [19]:
#splitting it into multiple array
np.split(d1,[1,3])

[array([4]), array([7, 1]), array([3, 9])]